### ISSUE TITLE
Travis setup isn't testing x86 support correctly?

### ISSUE THREAD

**Issue by rouge8** [dcreager/libcork#109]
As part of #108, I made a few fixes for 32-bit compatibility. In theory, our Travis build includes `ARCH=i386`, but that didn't catch the long constants from before eb06f032d52d7bb2d2eeae1ddc2b20c98d07ab9f...

**Comment by dcreager** [comment]
Our Travis builds always run on a 64-bit machine, even when we're testing under 32-bit mode.  (We just pass `-m32` to the compiler to activate 32-bit mode.)  I'm open to a more thorough testing setup if someone wants to invest the time in putting one together, but in the absence of that I think this is WAI.
