### ISSUE TITLE
Hash test fails on 64-bit big endian CPU architecture

### ISSUE THREAD

**Issue by rogers0** [dcreager/libcork#111]
Hash test fails on 64-bit big endian CPU architecture, such as s390x, ppc64 and sparc64:
`/«BUILDDIR»/libcork-0.15.0+ds/tests/test-core.c:341:F:hash:test_hash:0: Unexpected hash value 0xac7d28cc (expected 0x74bde19d)`

Build log can be referenced:
https://buildd.debian.org/status/fetch.php?pkg=libcork&arch=s390x&ver=0.15.0%2Bds-1&stamp=1464961690
https://buildd.debian.org/status/fetch.php?pkg=libcork&arch=ppc64&ver=0.15.0%2Bds-1&stamp=1464961396
https://buildd.debian.org/status/fetch.php?pkg=libcork&arch=sparc64&ver=0.15.0%2Bds-1&stamp=1465008367

**Comment by rogers0** [comment]
I tried on debian s390x porterbox. error msg is:
libcork/tests/test-core.c:332:F:hash:test_hash:0: Unexpected hash value 0xac7d28cc (expected 0x74bde19d)

and related code is:
    test_hash_buf(BUF, LEN-1,
      /* little 32 */ 0xba6bd213,
      /*    big 32 */ 0x29d175e5,
      /* little 64 */ 0xac7d28cc,
      /*    big 64 */ 0x74bde19d);

so maybe for 64bit Arch, the result is the same as little endian?

**Comment by rogers0** [comment]
Added my result of hash test from s390x on https://github.com/redjack/libcork/pull/116

**Comment by dcreager** [comment]
Closed by #131
