### ISSUE TITLE
A potential null pointer bug

### ISSUE THREAD

**Issue by richardxx** [dcreager/libcork#120]
A potential bug is in the function "cork_slice_slice" of the file "libcork/ds/slice.c". See the bug report screenshot below:

![image](https://cloud.githubusercontent.com/assets/1880553/21012872/03023276-bd93-11e6-92d9-4da2f6165834.png)

When it goes to the else branch, variable "slice == nullptr" and it cannot be used directly at line 166.

We checked this piece of code is still exists in current develop branch of libcork.

**Comment by dcreager** [comment]
Roger, if you push up your Debian patch as a PR I'd be happy to merge it in.

**Comment by rogers0** [comment]
Thanks for the ping!
Here's the PR: #128

**Comment by dcreager** [comment]
Fixed in #128

**Comment by richardxx** [comment]
Thanks guys, finally you caught it.
