### ISSUE TITLE
ipset repository removed?

### ISSUE THREAD

**Issue by rogers0** [dcreager/libcork#122]
@gregvirgin @dcreager @johnzachary repository of ipset (https://github.com/redjack/ipset) got removed?

I'm debian pkg maintainer of libcork and ipset. There're increasing number of users around.
- https://qa.debian.org/popcon-graph.php?packages=libcork16
- https://qa.debian.org/popcon-graph.php?packages=libcorkipset1

So I hope ipset can be restored.
Thanks for your understanding!

**Comment by johnzachary** [comment]
Hi @rogers0. I wish I could help, but neither @dcreager nor I work for RedJack.

**Comment by gregvirgin** [comment]
It’s public again.

Greg

**Comment by gregvirgin** [comment]
I’d like to offer to transfer ownership of these repos to someone else. Or please fork them so I can delete them some time this year. We don’t use them and aren’t offering to support them.

Thanks,

Greg

**Comment by rogers0** [comment]
@gregvirgin thanks for restoring the repo!
I just want to keep the metadata of the project, not only the code, but also reported issues, pull requests, etc.

@johnzachary @dcreager would you take the ownership of the repos, that @gregvirgin offered to hand out? I think it's more proper because you're the two main author. thanks!

**Comment by dcreager** [comment]
I can take ownership.  I won't have time to do any ongoing development, but I'm happy to review and merge PRs.

**Comment by rogers0** [comment]
@gregvirgin 
Thanks for taking care of these repos these days!
As I said, it's better to keep the metadata of these repos, such as issues, pull requests, etc.
Since @dcreager volunteer to be able to take the ownership, could you kindly help to proceed?
It's really appreciated your kindness!

**Comment by gregvirgin** [comment]
@dcreager please remove your forks of ipset and libcork so I can transfer ownership to you.

**Comment by dcreager** [comment]
Done

**Comment by gregvirgin** [comment]
transfers initiated.

**Comment by dcreager** [comment]
The repos have been transferred, closing this issue
