### ISSUE TITLE
A problem in the tests.

### ISSUE THREAD

**Issue by DDoSolitary** [dcreager/libcork#124]
`cork_path_user_runtime_path()` is run at last ([cork-test.c#L500](https://github.com/gregvirgin/libcork/blob/0231641bca541e80e82519b7a2933cfed02023c9/src/cork-test/cork-test.c#L500)), but the test file expects the error is outputted first ([run-paths-01#L14](https://github.com/gregvirgin/libcork/blob/0231641bca541e80e82519b7a2933cfed02023c9//tests/cork-test/run-paths-01.t#L14)).

**Comment by DDoSolitary** [comment]
I did some further investigation and it seems that there is multithreading involved and the output is specific to the implementation of libc being used. Most Linux distros use glibc and works fine with the tests, but Alpine Linux uses musl and it outputs in a different order. Finally give up to get the tests passed...

**Comment by dcreager** [comment]
I think the non-deterministic part is how stdout and stderr are being interleaved together by our test harness.  I've coded up #129 that only use stdout; can you check on your Alpine Linux box to see if that has fixed the issue?

**Comment by dcreager** [comment]
[Reopening pending confirmation from reporter]

**Comment by DDoSolitary** [comment]
Now the tests work well. Thank you very much!
