### ISSUE TITLE
Documentation about cork_delete

### ISSUE THREAD

**Issue by scossu** [dcreager/libcork#155]
The API docs have this signature for `cork_delete`: 

> type *cork_delete(void *ptr, TYPE type)

However, the [source code](https://github.com/dcreager/libcork/blob/master/include/libcork/core/allocator.h#L343) defines the parameters differently: 

```
#define cork_delete(type, ptr)  cork_free((ptr), sizeof(type))
```

Should the parameters in the documentation not be swapped? 

Also, if `cork_delete` is an alias for `cork_free` which returns `void *`, shouldn't the return type be `void *` too?

**Comment by dcreager** [comment]
Good catch, @scossu!  You're absolutely right, the parameters are backwards in the docs for `cork_delete`.  The return types for all three of those functions are wrong, too — they all return `void`, not any pointer value.  I opened up #156 with a fix.
